# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_optionsDialog(object):
    def setupUi(self, optionsDialog):
        optionsDialog.setObjectName("optionsDialog")
        optionsDialog.resize(454, 253)
        self.locationCountLabel = QtWidgets.QLabel(optionsDialog)
        self.locationCountLabel.setGeometry(QtCore.QRect(96, 223, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.locationCountLabel.setFont(font)
        self.locationCountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.locationCountLabel.setObjectName("locationCountLabel")
        self.reloadButton = QtWidgets.QPushButton(optionsDialog)
        self.reloadButton.setGeometry(QtCore.QRect(293, 217, 30, 30))
        self.reloadButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sartopo_address/reload-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadButton.setIcon(icon)
        self.reloadButton.setIconSize(QtCore.QSize(24, 24))
        self.reloadButton.setObjectName("reloadButton")
        self.locationFileField = QtWidgets.QLineEdit(optionsDialog)
        self.locationFileField.setGeometry(QtCore.QRect(15, 130, 342, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.locationFileField.setFont(font)
        self.locationFileField.setObjectName("locationFileField")
        self.label = QtWidgets.QLabel(optionsDialog)
        self.label.setGeometry(QtCore.QRect(15, 110, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.browseForLocationFileButton = QtWidgets.QPushButton(optionsDialog)
        self.browseForLocationFileButton.setGeometry(QtCore.QRect(370, 129, 71, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.browseForLocationFileButton.setFont(font)
        self.browseForLocationFileButton.setObjectName("browseForLocationFileButton")
        self.closeButton = QtWidgets.QPushButton(optionsDialog)
        self.closeButton.setGeometry(QtCore.QRect(349, 219, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.folderComboBox = STSFeatureComboBox(optionsDialog)
        self.folderComboBox.setGeometry(QtCore.QRect(257, 83, 185, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.folderComboBox.setFont(font)
        self.folderComboBox.setObjectName("folderComboBox")
        self.label_2 = QtWidgets.QLabel(optionsDialog)
        self.label_2.setGeometry(QtCore.QRect(14, 85, 232, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(optionsDialog)
        self.label_3.setGeometry(QtCore.QRect(13, 16, 127, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.urlField = QtWidgets.QLineEdit(optionsDialog)
        self.urlField.setGeometry(QtCore.QRect(141, 6, 276, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.urlField.setFont(font)
        self.urlField.setObjectName("urlField")
        self.linkIndicator = QtWidgets.QLineEdit(optionsDialog)
        self.linkIndicator.setEnabled(False)
        self.linkIndicator.setGeometry(QtCore.QRect(421, 5, 22, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.linkIndicator.setFont(font)
        self.linkIndicator.setObjectName("linkIndicator")
        self.accountNameLabel = QtWidgets.QLabel(optionsDialog)
        self.accountNameLabel.setEnabled(False)
        self.accountNameLabel.setGeometry(QtCore.QRect(15, 54, 170, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.accountNameLabel.setFont(font)
        self.accountNameLabel.setObjectName("accountNameLabel")
        self.accountNameField = QtWidgets.QLineEdit(optionsDialog)
        self.accountNameField.setEnabled(False)
        self.accountNameField.setGeometry(QtCore.QRect(187, 54, 255, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.accountNameField.setFont(font)
        self.accountNameField.setObjectName("accountNameField")
        self.markerFileField = QtWidgets.QLineEdit(optionsDialog)
        self.markerFileField.setGeometry(QtCore.QRect(15, 180, 342, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.markerFileField.setFont(font)
        self.markerFileField.setObjectName("markerFileField")
        self.browseForMarkerFileButton = QtWidgets.QPushButton(optionsDialog)
        self.browseForMarkerFileButton.setGeometry(QtCore.QRect(370, 179, 71, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.browseForMarkerFileButton.setFont(font)
        self.browseForMarkerFileButton.setObjectName("browseForMarkerFileButton")
        self.label_4 = QtWidgets.QLabel(optionsDialog)
        self.label_4.setGeometry(QtCore.QRect(15, 160, 179, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(optionsDialog)
        self.reloadButton.clicked.connect(optionsDialog.reload)
        self.closeButton.clicked.connect(optionsDialog.reject)
        self.urlField.editingFinished.connect(optionsDialog.urlEditingFinished)
        self.locationFileField.editingFinished.connect(optionsDialog.locationFileEditingFinished)
        self.folderComboBox.currentIndexChanged['QString'].connect(optionsDialog.folderComboBoxIndexChanged)
        self.markerFileField.editingFinished.connect(optionsDialog.markerFileEditingFinished)
        self.browseForMarkerFileButton.clicked.connect(optionsDialog.browseForMarkerFile)
        self.browseForLocationFileButton.clicked.connect(optionsDialog.browseForLocationFile)
        self.accountNameField.textChanged['QString'].connect(optionsDialog.accountNameTextChanged)
        QtCore.QMetaObject.connectSlotsByName(optionsDialog)
        optionsDialog.setTabOrder(self.urlField, self.accountNameField)
        optionsDialog.setTabOrder(self.accountNameField, self.folderComboBox)
        optionsDialog.setTabOrder(self.folderComboBox, self.locationFileField)
        optionsDialog.setTabOrder(self.locationFileField, self.browseForLocationFileButton)
        optionsDialog.setTabOrder(self.browseForLocationFileButton, self.markerFileField)
        optionsDialog.setTabOrder(self.markerFileField, self.browseForMarkerFileButton)
        optionsDialog.setTabOrder(self.browseForMarkerFileButton, self.reloadButton)
        optionsDialog.setTabOrder(self.reloadButton, self.closeButton)
        optionsDialog.setTabOrder(self.closeButton, self.linkIndicator)

    def retranslateUi(self, optionsDialog):
        _translate = QtCore.QCoreApplication.translate
        optionsDialog.setWindowTitle(_translate("optionsDialog", "Options"))
        self.locationCountLabel.setText(_translate("optionsDialog", "0 Locations loaded"))
        self.label.setText(_translate("optionsDialog", "Location Lookup File (.csv):"))
        self.browseForLocationFileButton.setText(_translate("optionsDialog", "Browse"))
        self.closeButton.setText(_translate("optionsDialog", "Close"))
        self.label_2.setText(_translate("optionsDialog", "Only list existing markers from fodler(s):"))
        self.label_3.setText(_translate("optionsDialog", "Saved map URL:"))
        self.accountNameLabel.setText(_translate("optionsDialog", "Sartopo.com account name:"))
        self.browseForMarkerFileButton.setText(_translate("optionsDialog", "Browse"))
        self.label_4.setText(_translate("optionsDialog", "Marker Definition File (.csv):"))

from  STSFeatureComboBox import STSFeatureComboBox
import sartopo_address_rc
