# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sartopo_address.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 138)
        self.addrField = QtWidgets.QLineEdit(Dialog)
        self.addrField.setGeometry(QtCore.QRect(88, 4, 390, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.addrField.setFont(font)
        self.addrField.setObjectName("addrField")
        self.latField = QtWidgets.QLineEdit(Dialog)
        self.latField.setEnabled(False)
        self.latField.setGeometry(QtCore.QRect(33, 49, 91, 22))
        self.latField.setObjectName("latField")
        self.lonField = QtWidgets.QLineEdit(Dialog)
        self.lonField.setEnabled(False)
        self.lonField.setGeometry(QtCore.QRect(158, 49, 98, 22))
        self.lonField.setObjectName("lonField")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(12, 13, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(-24, 53, 53, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 52, 64, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.newMarkerButton = QtWidgets.QPushButton(Dialog)
        self.newMarkerButton.setEnabled(False)
        self.newMarkerButton.setGeometry(QtCore.QRect(266, 89, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.newMarkerButton.setFont(font)
        self.newMarkerButton.setObjectName("newMarkerButton")
        self.locationCountLabel = QtWidgets.QLabel(Dialog)
        self.locationCountLabel.setGeometry(QtCore.QRect(73, 79, 176, 20))
        self.locationCountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.locationCountLabel.setObjectName("locationCountLabel")
        self.optionsButton = QtWidgets.QPushButton(Dialog)
        self.optionsButton.setGeometry(QtCore.QRect(436, 89, 41, 41))
        self.optionsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sartopo_address/options_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optionsButton.setIcon(icon)
        self.optionsButton.setIconSize(QtCore.QSize(30, 30))
        self.optionsButton.setObjectName("optionsButton")
        self.markerComboBox = QtWidgets.QComboBox(Dialog)
        self.markerComboBox.setEnabled(True)
        self.markerComboBox.setGeometry(QtCore.QRect(267, 49, 210, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.markerComboBox.setFont(font)
        self.markerComboBox.setIconSize(QtCore.QSize(30, 30))
        self.markerComboBox.setFrame(True)
        self.markerComboBox.setObjectName("markerComboBox")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/assisted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/evacuated.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/rescued.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/follow_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/animal_issue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/shelter_in_place.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_no_damage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_damaged.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_failed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_destroyed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/route_blocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon13, "")
        self.editMarkerComboBox = STSFeatureComboBox(Dialog)
        self.editMarkerComboBox.setEnabled(False)
        self.editMarkerComboBox.setGeometry(QtCore.QRect(350, 90, 83, 39))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.editMarkerComboBox.setFont(font)
        self.editMarkerComboBox.setObjectName("editMarkerComboBox")
        self.editMarkerComboBox.addItem("")
        self.linkIndicator = QtWidgets.QLineEdit(Dialog)
        self.linkIndicator.setEnabled(False)
        self.linkIndicator.setGeometry(QtCore.QRect(44, 75, 57, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linkIndicator.setFont(font)
        self.linkIndicator.setAlignment(QtCore.Qt.AlignCenter)
        self.linkIndicator.setObjectName("linkIndicator")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(11, 83, 32, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        self.addrField.editingFinished.connect(Dialog.lookupFromAddrField)
        self.newMarkerButton.clicked.connect(Dialog.addMarker)
        self.editMarkerComboBox.activated['int'].connect(Dialog.editMarker)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SARTopo Offline Address Search"))
        self.label.setText(_translate("Dialog", "Address"))
        self.label_2.setText(_translate("Dialog", "Lat"))
        self.label_3.setText(_translate("Dialog", "Lon"))
        self.newMarkerButton.setText(_translate("Dialog", "New"))
        self.locationCountLabel.setText(_translate("Dialog", "0 Locations loaded"))
        self.markerComboBox.setItemText(0, _translate("Dialog", "Default"))
        self.markerComboBox.setItemText(1, _translate("Dialog", "Assisted"))
        self.markerComboBox.setItemText(2, _translate("Dialog", "Evacuated"))
        self.markerComboBox.setItemText(3, _translate("Dialog", "Rescued"))
        self.markerComboBox.setItemText(4, _translate("Dialog", "Follow-up"))
        self.markerComboBox.setItemText(5, _translate("Dialog", "Animal Issue"))
        self.markerComboBox.setItemText(6, _translate("Dialog", "Shelter In Place"))
        self.markerComboBox.setItemText(7, _translate("Dialog", "No Damage"))
        self.markerComboBox.setItemText(8, _translate("Dialog", "Damaged"))
        self.markerComboBox.setItemText(9, _translate("Dialog", "Failed"))
        self.markerComboBox.setItemText(10, _translate("Dialog", "Destroyed"))
        self.markerComboBox.setItemText(11, _translate("Dialog", "Warning"))
        self.markerComboBox.setItemText(12, _translate("Dialog", "Route Blocked"))
        self.editMarkerComboBox.setItemText(0, _translate("Dialog", "Edit"))
        self.label_4.setText(_translate("Dialog", "Link:"))

from  STSFeatureComboBox import STSFeatureComboBox
import sartopo_address_rc
