# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sartopo_address.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 162)
        self.addrField = QtWidgets.QLineEdit(Dialog)
        self.addrField.setGeometry(QtCore.QRect(88, 4, 404, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.addrField.setFont(font)
        self.addrField.setObjectName("addrField")
        self.latLonField = QtWidgets.QLineEdit(Dialog)
        self.latLonField.setEnabled(True)
        self.latLonField.setGeometry(QtCore.QRect(276, 48, 195, 22))
        self.latLonField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.latLonField.setStyleSheet("background:#f0f0f0;color:#666666")
        self.latLonField.setDragEnabled(True)
        self.latLonField.setReadOnly(True)
        self.latLonField.setObjectName("latLonField")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(12, 13, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.locationCountLabel = QtWidgets.QLabel(Dialog)
        self.locationCountLabel.setGeometry(QtCore.QRect(96, 49, 161, 20))
        self.locationCountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.locationCountLabel.setObjectName("locationCountLabel")
        self.optionsButton = QtWidgets.QPushButton(Dialog)
        self.optionsButton.setGeometry(QtCore.QRect(478, 44, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.optionsButton.setFont(font)
        self.optionsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.optionsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sartopo_address/options_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optionsButton.setIcon(icon)
        self.optionsButton.setIconSize(QtCore.QSize(24, 24))
        self.optionsButton.setObjectName("optionsButton")
        self.markerSymbolComboBox = QtWidgets.QComboBox(Dialog)
        self.markerSymbolComboBox.setEnabled(True)
        self.markerSymbolComboBox.setGeometry(QtCore.QRect(92, 78, 245, 38))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.markerSymbolComboBox.setFont(font)
        self.markerSymbolComboBox.setMaxVisibleItems(20)
        self.markerSymbolComboBox.setIconSize(QtCore.QSize(30, 30))
        self.markerSymbolComboBox.setFrame(True)
        self.markerSymbolComboBox.setObjectName("markerSymbolComboBox")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/assisted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/evacuated.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/rescued.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/follow_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/animal_issue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/shelter_in_place.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_no_damage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_damaged.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_failed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_destroyed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/route_blocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon13, "")
        self.linkIndicator = QtWidgets.QLineEdit(Dialog)
        self.linkIndicator.setEnabled(False)
        self.linkIndicator.setGeometry(QtCore.QRect(38, 46, 56, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linkIndicator.setFont(font)
        self.linkIndicator.setFocusPolicy(QtCore.Qt.NoFocus)
        self.linkIndicator.setAlignment(QtCore.Qt.AlignCenter)
        self.linkIndicator.setObjectName("linkIndicator")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 50, 32, 18))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.goButton = QtWidgets.QPushButton(Dialog)
        self.goButton.setGeometry(QtCore.QRect(440, 84, 70, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.goButton.setFont(font)
        self.goButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.goButton.setObjectName("goButton")
        self.modeComboBox = QtWidgets.QComboBox(Dialog)
        self.modeComboBox.setEnabled(True)
        self.modeComboBox.setGeometry(QtCore.QRect(11, 78, 74, 38))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.modeComboBox.setFont(font)
        self.modeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.modeComboBox.setIconSize(QtCore.QSize(30, 30))
        self.modeComboBox.setFrame(True)
        self.modeComboBox.setObjectName("modeComboBox")
        self.modeComboBox.addItem("")
        self.modeComboBox.addItem("")
        self.modeComboBox.addItem("")
        self.existingMarkerComboBox = STSFeatureComboBox(Dialog)
        self.existingMarkerComboBox.setEnabled(True)
        self.existingMarkerComboBox.setGeometry(QtCore.QRect(92, 78, 245, 38))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.existingMarkerComboBox.setFont(font)
        self.existingMarkerComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.existingMarkerComboBox.setMaxVisibleItems(20)
        self.existingMarkerComboBox.setIconSize(QtCore.QSize(30, 30))
        self.existingMarkerComboBox.setFrame(True)
        self.existingMarkerComboBox.setObjectName("existingMarkerComboBox")
        self.existingMarkerComboBox.addItem("")
        self.timestampField = QtWidgets.QLineEdit(Dialog)
        self.timestampField.setGeometry(QtCore.QRect(343, 94, 88, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timestampField.setFont(font)
        self.timestampField.setText("")
        self.timestampField.setObjectName("timestampField")
        self.timestampLabel = QtWidgets.QLabel(Dialog)
        self.timestampLabel.setGeometry(QtCore.QRect(342, 72, 47, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.timestampLabel.setFont(font)
        self.timestampLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timestampLabel.setObjectName("timestampLabel")
        self.timestampCheckbox = QtWidgets.QCheckBox(Dialog)
        self.timestampCheckbox.setGeometry(QtCore.QRect(405, 73, 30, 20))
        self.timestampCheckbox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.timestampCheckbox.setText("")
        self.timestampCheckbox.setIconSize(QtCore.QSize(16, 16))
        self.timestampCheckbox.setChecked(True)
        self.timestampCheckbox.setObjectName("timestampCheckbox")
        self.clearAddressButton = QtWidgets.QPushButton(Dialog)
        self.clearAddressButton.setGeometry(QtCore.QRect(490, 3, 20, 39))
        self.clearAddressButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clearAddressButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/sartopo_address/tall_x_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearAddressButton.setIcon(icon14)
        self.clearAddressButton.setIconSize(QtCore.QSize(12, 30))
        self.clearAddressButton.setObjectName("clearAddressButton")
        self.folderComboBox = STSFeatureComboBox(Dialog)
        self.folderComboBox.setEnabled(True)
        self.folderComboBox.setGeometry(QtCore.QRect(11, 124, 177, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.folderComboBox.setFont(font)
        self.folderComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.folderComboBox.setEditable(False)
        self.folderComboBox.setIconSize(QtCore.QSize(30, 30))
        self.folderComboBox.setFrame(True)
        self.folderComboBox.setObjectName("folderComboBox")
        self.folderComboBox.addItem("")
        self.commentField = QtWidgets.QLineEdit(Dialog)
        self.commentField.setGeometry(QtCore.QRect(271, 125, 160, 25))
        self.commentField.setObjectName("commentField")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(196, 127, 70, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        self.addrField.editingFinished.connect(Dialog.lookupFromAddrField)
        self.modeComboBox.currentIndexChanged['int'].connect(Dialog.modeChanged)
        self.goButton.released.connect(Dialog.go)
        self.clearAddressButton.released.connect(Dialog.clearAddress)
        self.timestampCheckbox.released.connect(Dialog.timestampCheckboxCB)
        self.existingMarkerComboBox.currentIndexChanged['int'].connect(Dialog.existingMarkerComboBoxCB)
        self.markerSymbolComboBox.currentIndexChanged['int'].connect(Dialog.markerSymbolComboBoxCB)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SARTopo Address Tool"))
        self.latLonField.setPlaceholderText(_translate("Dialog", "Lat/Lon (D.d)"))
        self.label.setText(_translate("Dialog", "Address"))
        self.locationCountLabel.setText(_translate("Dialog", "0 Locations loaded"))
        self.markerSymbolComboBox.setItemText(0, _translate("Dialog", "Default"))
        self.markerSymbolComboBox.setItemText(1, _translate("Dialog", "Assisted"))
        self.markerSymbolComboBox.setItemText(2, _translate("Dialog", "Evacuated"))
        self.markerSymbolComboBox.setItemText(3, _translate("Dialog", "Rescued"))
        self.markerSymbolComboBox.setItemText(4, _translate("Dialog", "Follow-up"))
        self.markerSymbolComboBox.setItemText(5, _translate("Dialog", "Animal Issue"))
        self.markerSymbolComboBox.setItemText(6, _translate("Dialog", "Shelter In Place"))
        self.markerSymbolComboBox.setItemText(7, _translate("Dialog", "No Damage"))
        self.markerSymbolComboBox.setItemText(8, _translate("Dialog", "Damaged"))
        self.markerSymbolComboBox.setItemText(9, _translate("Dialog", "Failed"))
        self.markerSymbolComboBox.setItemText(10, _translate("Dialog", "Destroyed"))
        self.markerSymbolComboBox.setItemText(11, _translate("Dialog", "Warning"))
        self.markerSymbolComboBox.setItemText(12, _translate("Dialog", "Route Blocked"))
        self.label_4.setText(_translate("Dialog", "Map"))
        self.goButton.setText(_translate("Dialog", "Go"))
        self.modeComboBox.setItemText(0, _translate("Dialog", "Mode"))
        self.modeComboBox.setItemText(1, _translate("Dialog", "Add"))
        self.modeComboBox.setItemText(2, _translate("Dialog", "Move"))
        self.existingMarkerComboBox.setItemText(0, _translate("Dialog", "Existing Marker"))
        self.timestampLabel.setText(_translate("Dialog", "Time"))
        self.folderComboBox.setItemText(0, _translate("Dialog", "Folder"))
        self.label_5.setText(_translate("Dialog", "Comment"))

from  STSFeatureComboBox import STSFeatureComboBox
import sartopo_address_rc
