# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sartopo_address.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 162)
        self.addrField = QtWidgets.QLineEdit(Dialog)
        self.addrField.setGeometry(QtCore.QRect(88, 4, 404, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.addrField.setFont(font)
        self.addrField.setObjectName("addrField")
        self.latField = QtWidgets.QLineEdit(Dialog)
        self.latField.setEnabled(False)
        self.latField.setGeometry(QtCore.QRect(39, 49, 166, 22))
        self.latField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.latField.setObjectName("latField")
        self.lonField = QtWidgets.QLineEdit(Dialog)
        self.lonField.setEnabled(False)
        self.lonField.setGeometry(QtCore.QRect(256, 48, 167, 22))
        self.lonField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lonField.setObjectName("lonField")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(12, 13, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(-24, 53, 53, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(185, 53, 64, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.locationCountLabel = QtWidgets.QLabel(Dialog)
        self.locationCountLabel.setGeometry(QtCore.QRect(108, 78, 176, 20))
        self.locationCountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.locationCountLabel.setObjectName("locationCountLabel")
        self.optionsButton = QtWidgets.QPushButton(Dialog)
        self.optionsButton.setGeometry(QtCore.QRect(469, 49, 41, 41))
        self.optionsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.optionsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sartopo_address/options_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optionsButton.setIcon(icon)
        self.optionsButton.setIconSize(QtCore.QSize(30, 30))
        self.optionsButton.setObjectName("optionsButton")
        self.markerSymbolComboBox = QtWidgets.QComboBox(Dialog)
        self.markerSymbolComboBox.setEnabled(True)
        self.markerSymbolComboBox.setGeometry(QtCore.QRect(111, 112, 285, 39))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.markerSymbolComboBox.setFont(font)
        self.markerSymbolComboBox.setMaxVisibleItems(20)
        self.markerSymbolComboBox.setIconSize(QtCore.QSize(30, 30))
        self.markerSymbolComboBox.setFrame(True)
        self.markerSymbolComboBox.setObjectName("markerSymbolComboBox")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/assisted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/evacuated.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/rescued.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/follow_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/animal_issue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/shelter_in_place.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_no_damage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_damaged.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_failed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/structure_destroyed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/sartopo_address/sartopo_markers/route_blocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerSymbolComboBox.addItem(icon13, "")
        self.linkIndicator = QtWidgets.QLineEdit(Dialog)
        self.linkIndicator.setEnabled(False)
        self.linkIndicator.setGeometry(QtCore.QRect(44, 75, 67, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linkIndicator.setFont(font)
        self.linkIndicator.setFocusPolicy(QtCore.Qt.NoFocus)
        self.linkIndicator.setAlignment(QtCore.Qt.AlignCenter)
        self.linkIndicator.setObjectName("linkIndicator")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(11, 83, 32, 16))
        self.label_4.setObjectName("label_4")
        self.goButton = QtWidgets.QPushButton(Dialog)
        self.goButton.setGeometry(QtCore.QRect(440, 96, 70, 56))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.goButton.setFont(font)
        self.goButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.goButton.setObjectName("goButton")
        self.modeComboBox = QtWidgets.QComboBox(Dialog)
        self.modeComboBox.setEnabled(True)
        self.modeComboBox.setGeometry(QtCore.QRect(9, 112, 88, 39))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.modeComboBox.setFont(font)
        self.modeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.modeComboBox.setIconSize(QtCore.QSize(30, 30))
        self.modeComboBox.setFrame(True)
        self.modeComboBox.setObjectName("modeComboBox")
        self.modeComboBox.addItem("")
        self.modeComboBox.addItem("")
        self.modeComboBox.addItem("")
        self.existingMarkerComboBox = STSFeatureComboBox(Dialog)
        self.existingMarkerComboBox.setEnabled(True)
        self.existingMarkerComboBox.setGeometry(QtCore.QRect(111, 112, 169, 39))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.existingMarkerComboBox.setFont(font)
        self.existingMarkerComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.existingMarkerComboBox.setMaxVisibleItems(20)
        self.existingMarkerComboBox.setIconSize(QtCore.QSize(30, 30))
        self.existingMarkerComboBox.setFrame(True)
        self.existingMarkerComboBox.setObjectName("existingMarkerComboBox")
        self.existingMarkerComboBox.addItem("")
        self.timestampField = QtWidgets.QLineEdit(Dialog)
        self.timestampField.setGeometry(QtCore.QRect(369, 117, 64, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timestampField.setFont(font)
        self.timestampField.setObjectName("timestampField")
        self.timestampLabel = QtWidgets.QLabel(Dialog)
        self.timestampLabel.setGeometry(QtCore.QRect(298, 111, 47, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.timestampLabel.setFont(font)
        self.timestampLabel.setObjectName("timestampLabel")
        self.timestampCheckbox = QtWidgets.QCheckBox(Dialog)
        self.timestampCheckbox.setGeometry(QtCore.QRect(348, 121, 30, 20))
        self.timestampCheckbox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.timestampCheckbox.setText("")
        self.timestampCheckbox.setChecked(True)
        self.timestampCheckbox.setObjectName("timestampCheckbox")
        self.clearAddressButton = QtWidgets.QPushButton(Dialog)
        self.clearAddressButton.setGeometry(QtCore.QRect(490, 3, 20, 39))
        self.clearAddressButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clearAddressButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/sartopo_address/tall_x_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearAddressButton.setIcon(icon14)
        self.clearAddressButton.setIconSize(QtCore.QSize(12, 30))
        self.clearAddressButton.setObjectName("clearAddressButton")

        self.retranslateUi(Dialog)
        self.addrField.editingFinished.connect(Dialog.lookupFromAddrField)
        self.modeComboBox.currentIndexChanged['int'].connect(Dialog.modeChanged)
        self.goButton.released.connect(Dialog.go)
        self.clearAddressButton.released.connect(Dialog.clearAddress)
        self.timestampCheckbox.released.connect(Dialog.timestampCheckboxCB)
        self.existingMarkerComboBox.currentIndexChanged['int'].connect(Dialog.existingMarkerComboBoxCB)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SARTopo Offline Address Search"))
        self.label.setText(_translate("Dialog", "Address"))
        self.label_2.setText(_translate("Dialog", "Lat"))
        self.label_3.setText(_translate("Dialog", "Lon"))
        self.locationCountLabel.setText(_translate("Dialog", "0 Locations loaded"))
        self.markerSymbolComboBox.setItemText(0, _translate("Dialog", "Default"))
        self.markerSymbolComboBox.setItemText(1, _translate("Dialog", "Assisted"))
        self.markerSymbolComboBox.setItemText(2, _translate("Dialog", "Evacuated"))
        self.markerSymbolComboBox.setItemText(3, _translate("Dialog", "Rescued"))
        self.markerSymbolComboBox.setItemText(4, _translate("Dialog", "Follow-up"))
        self.markerSymbolComboBox.setItemText(5, _translate("Dialog", "Animal Issue"))
        self.markerSymbolComboBox.setItemText(6, _translate("Dialog", "Shelter In Place"))
        self.markerSymbolComboBox.setItemText(7, _translate("Dialog", "No Damage"))
        self.markerSymbolComboBox.setItemText(8, _translate("Dialog", "Damaged"))
        self.markerSymbolComboBox.setItemText(9, _translate("Dialog", "Failed"))
        self.markerSymbolComboBox.setItemText(10, _translate("Dialog", "Destroyed"))
        self.markerSymbolComboBox.setItemText(11, _translate("Dialog", "Warning"))
        self.markerSymbolComboBox.setItemText(12, _translate("Dialog", "Route Blocked"))
        self.label_4.setText(_translate("Dialog", "Map:"))
        self.goButton.setText(_translate("Dialog", "Go"))
        self.modeComboBox.setItemText(0, _translate("Dialog", "Mode"))
        self.modeComboBox.setItemText(1, _translate("Dialog", "Add"))
        self.modeComboBox.setItemText(2, _translate("Dialog", "Move"))
        self.existingMarkerComboBox.setItemText(0, _translate("Dialog", "Existing Marker"))
        self.timestampLabel.setText(_translate("Dialog", "Time"))

from  STSFeatureComboBox import STSFeatureComboBox
import sartopo_address_rc
